#!/usr/bin/env bash
# After configuring domain zone, use this script to output where each subdomain points to

function print_info(){
    dig "$2.$1" | awk '/ANSWER SECTION:/{getline; printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$SUBDOMAIN"
}

for SUBDOMAIN in "www" "lb-01" "web-01" "web-02"
do
    if [ -z "$2" ] || [ "$2" == "$SUBDOMAIN" ]; then
        print_info "$1" "$SUBDOMAIN"
    fi
done
