#!/usr/bin/env bash
# configure HAproxy

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo echo "
frontend web-frontend
        bind *:80
        mode http
        default_backend web-backend
backend web-backend
        balance roundrobin
	server 982-web-01 44.192.34.201:80 check
	server 982-web-02 34.231.70.69:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
sudo echo "ENABLE=1" >> /etc/default/haproxy
