#!/usr/bin/env bash
# parse logs  for IP and HTTP
# calculate and put num of counts up front; order from most to least

file="apache-access.log"
awk '{print $1, $9}' $file | sort | uniq -c | sort -nr
