#!/usr/bin/env bash
# Prints "Holberton School" 10x, "bad luck" the 4th, "good luck" the 8th
count=1
while [ "$count" -le 10 ]
do
    if [ "$count" -eq 4 ]; then
	echo "bad luck"
    elif [ "$count" -eq 8 ]; then
	echo "good luck"
    else
	echo "Best School"
    fi
    (( count++ ))
done
