#!/usr/bin/env bash
# Displays hours: 0-12, minutes 1-59

hour=0
while [ "$hour" -le 12 ]
do
    echo "Hour: $hour"
    (( hour++ ))

    min=1
    while [ "$min" -le 59 ]
    do
	echo "$min"
	(( min++ ))
    done
done
